name: Linux_BuildV8

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: master
  pull_request:
    branches: master
  watch:
    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ${{github.workspace}}

    if: github.event.repository.owner.id == github.event.sender.id


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # clone depot_tools
      - name: dclone depot_tools
        shell: bash
        working-directory: ${{env.working-directory}}
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          cd depot_tools
          gclient

     # checkut & build V8
      - name: checkut & build V8
        shell: bash
        working-directory: ${{env.working-directory}}
        run: |
          echo on
          
          PATH="$PATH:$(pwd)/depot_tools"
          
          echo "begin fetch V8"
          ./depot_tools/fetch V8
          echo "end fetch V8"
          
          cd V8
          
          echo "begin gclient sync"
          ./depot_tools/gclient sync
          echo "end gclient sync"
          
          python ./tools/dev/gm.py x64.release
