# This is a basic workflow to help you get started with Actions

name: Windows_BuildV8

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: master
  pull_request:
    branches: master
  watch:
    types: started 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: build v8
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo $pwd\depot_tools
          $env:PATH=$env:PATH+";$pwd\depot_tools"
          echo $env:Path
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set GYP_MSVS_VERSION=2019
          fetch v8
          cd v8
          gn gen --ide=vs out.gn\x64_solution
          python tools\dev\v8gen.py x64.release
          ninja -C out.gn\x64.release
